#!/bin/ash

endError() {
	if [ -e /sys/devices/platform/bubbatwo/ledfreq ] ; then
		echo 32768 > /sys/devices/platform/bubbatwo/ledfreq
		echo blink > /sys/devices/platform/bubbatwo/ledmode
	else
		echo 0 > /sys/class/leds/bubba3:green:programming/brightness
		echo 0 > /sys/class/leds/bubba3:blue:active/brightness
		echo 1 > /sys/class/leds/bubba3:red:error/brightness
	fi
	exec /bin/ash
}

unzip() {
	if [ -e /mnt/mnt/usb/install/rootfs.cpio.gz ] ; then
		echo "Copying step 2 files to tmpfs ..."
		zcat /mnt/mnt/usb/install/rootfs.cpio.gz | (cd /mnt ; cpio -id) || endError
		umount /sys
		exec switch_root /mnt /init
	else
		echo "roofs.cpio.gz not found !"
		endError
	fi
}

mount -t sysfs none /sys
mount -t tmpfs none /mnt
mkdir -p /mnt/mnt/usb
mount -t vfat /dev/sda1 /mnt/mnt/usb && unzip || sleep 2
mount -t vfat /dev/sda1 /mnt/mnt/usb && unzip || sleep 2
mount -t vfat /dev/sda1 /mnt/mnt/usb && unzip || sleep 2
mount -t vfat /dev/sda1 /mnt/mnt/usb && unzip || sleep 2
mount -t vfat /dev/sda1 /mnt/mnt/usb && unzip || sleep 2
endError
