#!/bin/sh

[ -x /opt/excito/installer ] || exit 0

start() {
    echo "Starting Excito installer ..."
    /opt/excito/installer
}

case "$1" in
  start)
    start
    ;;
  *)
    echo "Usage: $0 {start}"
    exit 1
esac
